environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 14
    - nodejs_version: 16
    - nodejs_version: 17

version: "{build}"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test
  - npm run cov:check
  - npm run cov:send

build: off
deploy: off